### ISSUE TITLE
[Bug] Chinese character duplication after chunking since version: 0.97.250211.1 (docker)

### ISSUE THREAD

**Issue by andrew0928** [microsoft/kernel-memory#1033]
### Context / Scenario

When processing a large Chinese document (in Markdown format, around 100 KB), the Chunker introduced in version 0.97.250211.1 starts duplicating certain Chinese characters right after a chunk boundary. Using the same Markdown file, if I switch the Docker image back to version 0.96.250120.1, this issue does not occur.

I extracted a sample file demonstrating this problem. In the _files\{documentId}\ folder, there is a file named *.partition.1.txt. Starting from the second chunk, it shows the following (actual content):

```
的開發發者大會會，發發布了一個個新的服務務
(ignored)
```

However, the expected content should be:

```
的開發者大會，發布了一個新的服務
(ignored)
```

As you can see, several Chinese characters are duplicated after the text is split by the chunker.

## Steps to Reproduce

1. Use a Markdown file (around 50 ~ 100 KB in size) that contains Chinese text.
1. Process the file with Chunker version 0.97.250211.1.
1. Observe that in subsequent chunks (e.g., the second chunk), some Chinese characters become duplicated.
1. Switch to version 0.96.250120.1 using the same file and confirm that the duplication issue does not occur.

## Expected Behavior
Text should remain consistent without any duplication after being split into chunks, just as it does in the previous Docker image version.

## Actual Behavior
Characters within the chunk boundary are duplicated, causing incorrect text output.

Please let me know if additional information or further examples are needed. Thank you!

### What happened?

[2024-01-15-archview-llm.md](https://github.com/user-attachments/files/19315172/2024-01-15-archview-llm.md)

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

Windows 11 24H2, run docker version in WSL2
use docker image: kernelmemory/service:0.97.250211.1-b-amd64

[0.97.250211.1-b-amd64](https://hub.docker.com/layers/kernelmemory/service/0.97.250211.1-b-amd64/images/sha256-fb29c7c13d1c9b5ed0b331c487875df3a4aa2d37f071023c8d51f331163bfd62)

### Relevant log output

```shell

```

**Comment by dluc** [comment]
Could you try the latest docker image?

**Comment by andrew0928** [comment]
No, the bug still there, not fixed in docker image: ```kernelmemory/service:0.98.250323.1-amd64```

I'll write some script to reproduce the problem later

**Comment by andrew0928** [comment]
**Comment: Reproduction Steps & Key Difference in Output**

I’m encountering a Chinese text duplication issue with the latest version (`0.98.250323.1`) of kernelmemory/service, whereas version `0.96.250120.1` yields the correct text.

---

### Environment
- **OS**: Windows 11 Pro, 24H2 (via WSL2)
- **Kernel Memory Service**: 
  - ✅ *`0.96.250120.1`* (works as expected)  
  - ❌ *`0.98.250323.1`* (exhibits duplication bug)
- **Model**: `4o-mini` and `text-embedding-large3`
- **Docker Compose File**:
  ```yaml
  services:
    km:
      image: kernelmemory/service:0.96.250120.1
      restart: always
      depends_on:
        - qdrant
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      ports:
        - "9001:9001"
      volumes:
        - ./appsettings.json:/app/appsettings.Development.json
        - ./_files:/app/_files
        - ./_queues:/app/_queues
        - ./_vectors:/app/_vectors
  
    qdrant:
      image: qdrant/qdrant
      restart: always
      ports:
        - 6333:6333
        - 6334:6334
      volumes:
        - ./_qdrant_data:/qdrant/storage
  ```

---

### Steps to Reproduce

1. **Run Kernel Memory Service**  
   - Using the above `docker-compose.yaml`, start up the service on WSL2.
2. **Upload Markdown File**  ( my test file: [test.md](https://github.com/user-attachments/files/19462248/test.md) )
   - Inside `/tools/km-cli/`, run:  
     ```bash
     ./upload-file.sh -s http://127.0.0.1:9001 -f test.md -p test -i testdocs
     ```
3. **Perform a Search**  
   - Still in `/tools/km-cli/`, run:  
     ```bash
     ./search.sh -s http://127.0.0.1:9001 -p test -l 1 -q "LLM"
     ```
4. **Compare Outputs**  
   - On version `0.98.250323.1`, the returned JSON contains duplicated characters for portions of Chinese text.  
   - On version `0.96.250120.1`, the text appears correctly with no duplication.

---

### Actual Output on `0.98.250323.1` (Incorrect)

Here is an excerpt where characters are duplicated and partially garbled:

```
UI 接接受受使用者的操作，UI 設設設計人員員就必須須負負擔擔擔把把他轉轉譯譯成 "正確確" API 的任務務，而這這 API 一路往往下層層傳傳傳遞遞，變變成呼呼叫叫其他服務務，或是存取資資料庫庫等等細細節節。
```

---

### Expected Output on `0.96.250120.1` (Correct)

Below is the same section from the older version (and matches the original `test.md` content):

```
UI 接受使用者的操作，UI 設計人員就必須負擔把他轉譯成 "正 確" API 的任務，而這 API 一路往下層傳遞，變成呼叫其他服務，或是存取資料庫等等細節。
```

*(Notice the absence of repeated or garbled characters.)*

---

Please let me know if you need any additional logs or the original `test.md` file for further debugging. I’m happy to provide more details as needed!
